<a href="https://colab.research.google.com/github/harshitbhandari23/univariate-ananlysis-non-graphical/blob/main/univariate_analysisnongraphical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as snp
df=pd.read_csv("AB_NYC_2019.csv")
df.dropna(inplace =True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38821 entries, 0 to 48852
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              38821 non-null  int64
 1   name                            38821 non-null  object
 2   host_id                         38821 non-null  int64
 3   host_name                       38821 non-null  object
 4   neighbourhood_group             38821 non-null  object
 5   neighbourhood                   38821 non-null  object
 6   latitude                        38821 non-null  float64
 7   longitude                       38821 non-null  float64
 8   room_type                       38821 non-null  object
 9   price                           38821 non-null  int64
 10  minimum_nights                  38821 non-null  int64
 11  number_of_reviews               38821 non-null  int64
 12  last_review                     38821 non-null  object
 13  reviews_per_month               38821 non-null  float64
 14  calculated_host_listings_count  38821 non-null  int64
 15  availability_365                38821 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 5.0+ MB

In [ ]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.975,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,Lovely Privet Bedroom with Privet Restroom,83554966,Rusaa,Manhattan,Upper East Side,40.78099,-73.95366,Private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,No.2 with queen size bed,257683179,H Ai,Queens,Flushing,40.75104,-73.81459,Private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,Seas The Moment,211644523,Ben,Staten Island,Great Kills,40.54179,-74.14275,Private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1B-1B apartment near by Metro,273841667,Blaine,Bronx,Mott Haven,40.80787,-73.924,Entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,40.69805,-73.92801,Private room,30,1,1,2019-07-08,1.00,1,1

In [ ]:
df["id"]=df["id"].astype("str")
df["host_id"]=df["host_id"].astype("str")
df["latitude"]=df["latitude"].astype("str")
df["longitude"]=df["longitude"].astype("str")

# using describe

In [ ]:
df.describe()

,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,38821.000000,38821.000000,38821.000000,38821.000000,38821.000000,38821.000000
mean,142.332526,5.869220,29.290255,1.373229,5.166611,114.886299
std,196.994756,17.389026,48.182900,1.680328,26.302954,129.529950
min,0.000000,1.000000,1.000000,0.010000,1.000000,0.000000
25%,69.000000,1.000000,3.000000,0.190000,1.000000,0.000000
50%,101.000000,2.000000,9.000000,0.720000,1.000000,55.000000
75%,170.000000,4.000000,33.000000,2.020000,2.000000,229.000000
max,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [ ]:
df.nunique()

id                                38821
name                              38253
host_id                           30232
host_name                          9885
neighbourhood_group                   5
neighbourhood                       218
latitude                          17436
longitude                         13639
room_type                             3
price                               581
minimum_nights                       89
number_of_reviews                   393
last_review                        1764
reviews_per_month                   937
calculated_host_listings_count       47
availability_365                    366
dtype: int64

# categorical analysis

In [ ]:
df["neighbourhood_group"].value_counts()

neighbourhood_group
Manhattan        16621
Brooklyn         16439
Queens            4572
Bronx              875
Staten Island      314
Name: count, dtype: int64

In [ ]:
df["room_type"].value_counts()

room_type
Entire home/apt    20321
Private room       17654
Shared room          846
Name: count, dtype: int64

In [ ]:
df1=df["neighbourhood"].value_counts().reset_index()
df1

          neighbourhood  count
0          Williamsburg   3163
1    Bedford-Stuyvesant   3141
2                Harlem   2204
3              Bushwick   1942
4        Hell's Kitchen   1528
..                  ...    ...
213           Olinville      2
214      New Dorp Beach      2
215        Richmondtown      1
216           Rossville      1
217         Willowbrook      1

[218 rows x 2 columns]

# neighbours with no.oh hotels greater than 1000

In [ ]:
df1[df1["count"]>1000]

        neighbourhood  count
0        Williamsburg   3163
1  Bedford-Stuyvesant   3141
2              Harlem   2204
3            Bushwick   1942
4      Hell's Kitchen   1528
5        East Village   1489
6     Upper West Side   1482
7     Upper East Side   1405
8       Crown Heights   1265

# numerical analysis

In [ ]:
df["price"].value_counts(bins=5)

(-10.001, 2000.0]    38786
(2000.0, 4000.0]        20
(4000.0, 6000.0]         8
(8000.0, 10000.0]        5
(6000.0, 8000.0]         2
Name: count, dtype: int64

In [ ]:
df["price"].mean()

np.float64(142.33252621004095)

In [ ]:
df["price"].std()

np.float64(196.9947559183469)

In [ ]:
df["price"].skew()

np.float64(23.673594295123014)

In [ ]:
df["price"].kurt()

np.float64(953.4807356344945)

In [ ]:
df.corr()

ValueError: could not convert string to float: 'Clean & quiet apt home by the park'